# [build] 섹션은 빌드에 관한 전반적인 설정을 담당합니다.
[build]
  # ★★★ 함수 디렉토리를 여기서 지정하는 것이 가장 안정적입니다.
  functions = "netlify/functions"
  
  # 만약 사용하는 빌드 명령어나 publish 폴더가 있다면 여기에 둡니다.
  # command = "npm run build"
  # publish = "public"

# [functions] 섹션은 모든 함수에 공통으로 적용될 설정을 담당합니다.
# "어떤 파일들을 추가로 포함할 것인가?" 와 같은 설정을 넣습니다.
[functions]
  included_files = ["netlify/functions/modules/**"]